;/* Version 7ee08ffc80eb95c73b3f07237ad42c17 v:4.1.1.0, c:0aade7d14cdbcdd9a7a0092f24e7f52b1ffd1a72, b:7988 n:16-4.1.1.next-build */(function(){/*


 Copyright (c) 2013, AppDynamics, Inc. All rights reserved.

 Derivative of Google Episodes:

 Copyright 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

 http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.

 See the source code here:
 http://code.google.com/p/episodes/
*/
(function(){var g=window.ADRUM;g&&g.q&&!0!==window["adrum-disable"]&&(function(a){(function(c){function e(d){return"function"==typeof d||!1}function b(d){return"[object Array]"===Object.prototype.toString.apply(d)}c.Bb=e;c.isArray=b;c.wa=function(d){return"object"==typeof d&&!b(d)};c.va=function(d){return"undefined"!==typeof d&&null!==d};c.Yb=function(d){var f={a:[1,2,3,"str"]};if('{"a":[1,2,3,"str"]}'===JSON.stringify(f).replace(/\s/g,""))return JSON.stringify(d);var n=Object.toJSON;if("function"===
typeof n&&'{"a":[1,2,3,"str"]}'===n(f).replace(/\s/g,""))return a.error("M58"),n(d);a.error("M59");return null};c.Ye=function(d,f,a,b){function c(){if(f())a&&a();else{var g=d(++e);0<g?setTimeout(c,g):b&&b()}}var e=0;c()};c.now=function(){return(new Date).getTime()};c.ra=function(d,f,n){var b=d,c=n;"xhr"===n&&(b=document.createElement("div"),d.appendChild(b),c="xhr_"+d.getElementsByTagName("div").length);d=document.createElement("p");d.innerHTML="Script loaded from "+a.conf.adrumExtUrl+". Metrics collected are:";
b.appendChild(d);d=document.createElement("table");d.id="ADRUM_"+c;var c=document.createElement("tbody"),e;for(e in f){n=document.createElement("tr");var g=document.createElement("td");g.innerHTML=e;g.className="name";var k=document.createElement("td");k.innerHTML=String(f[e]);k.className="value";n.appendChild(g);n.appendChild(k);c.appendChild(n)}d.appendChild(c);b.appendChild(d)};c.yd=function(){function d(f,a){try{if("object"!=typeof f)return String(f);if(0<=c.ma(a,f))return"Already visited";a.push(f);
var l;if(b(f)){for(var e="[ ",g=0;g<f.length;g++)0!=g&&(e+=", "),e+=d(f[g],a);l=e+" ]"}else{var e="{ ",g=!0,h;for(h in f)g?g=!1:e+=", ",e+=d(h,a)+" => "+d(f[h],a);l=e+" }"}return l}catch(k){return"dumpObject failed: "+k}}return function(f){return d(f,[])}}();c.ma=e(Array.prototype.indexOf)?function(d,f){return d.indexOf(f)}:function(d,f){for(var a=0;a<d.length;a++)if(d[a]==f)return a;return-1};c.compareWindows=function(d,f){return d==f};c.Zb=function(d,f,a){if("undefined"===typeof f||null===f)return f;
if("object"==typeof f)for(var b in f)Object.prototype.hasOwnProperty.call(f,b)&&(f[b]=c.Zb(b,f[b],a));else e(f)||(f=a(d,f));return f};c.ke=function(d){var f=[],a;for(a in d)Object.prototype.hasOwnProperty.call(d,a)&&f.push([a,d[a]]);return f}})(a.utils||(a.utils={}))}(g||(g={})),function(a){(function(a){a.Wb=function(a){return/^[0-9]+$/.test(a)?Number(a):null};a.Ab=function(a){return"number"===typeof a&&!isNaN(a)&&isFinite(a)}})(a.utils||(a.utils={}))}(g||(g={})),function(a){(function(c){function e(f){var d=
f.split("\r\n"),b=/^\s*ADRUM_(\d+): (.+)\s*$/i;f=[];for(var c=0;c<d.length;c++){var e=d[c];try{var g=b.exec(e);g&&f.push([Number(g[1]),g[2]])}catch(k){a.exception(k,"M62",e)}}Array.prototype.sort.call(f,function(d,f){return d[0]-f[0]});g=[];for(d=0;d<f.length;d++)g.push(f[d][1]);return g}var b=null,d=null;c.ub=function(){d||(d=c.Ib(c.Ba(c.cookieMetadataChunks),c.Ba(a.footerMetadataChunks)));return d};c.getPageGUID=function(){if(!b){var d=c.ub();b=d&&d.clientRequestGUID||a.utils.generateGUID()}return b};
c.Sd=function(d){d=e(d);a.log("M60",d);return c.Ib(c.Ba(d))};c.Ib=function(d,n){function b(d){for(var f=0;f<d.length;f++){var n=d[f];n!=e&&0>a.utils.ma(k,n)&&k.push(n)}}if(!d||0>=d.B.length)return null;n||(n=d);var e;if(0<n.B.length){if(e=n.B[0],0>a.utils.ma(d.B,e))return null}else return a.error("M61"),null;var g=n.serverSnapshotType||d.serverSnapshotType,h=n.hasEntryPointErrors||d.hasEntryPointErrors,k=[];b(d.B);b(n.B);var q={clientRequestGUID:e};0<k.length&&(q.otherClientRequestGUIDs=k);0<c.Hb(d.btTime,
n.btTime).length&&(q.btTime=c.Hb(d.btTime,n.btTime));null!==g&&(q.serverSnapshotType=g);null!==h&&(q.hasEntryPointErrors=h);return q};c.Hb=function(d,a){for(var b=d.concat(a),c={},e={},g=0;g<b.length;g++){var k=b[g];k.id in c||(c[k.id]=-1);c[k.id]=Math.max(c[k.id],k.duration);k.id in e||(e[k.id]=-1);e[k.id]=Math.max(e[k.id],k.ert)}var b=[],q;for(q in c)c.hasOwnProperty(q)&&b.push({id:q,duration:c[q],ert:e[q]});return b};c.Ba=function(d){if(!a.utils.isArray(d))return null;for(var n=[],b=[],c=null,
e=null,g=0;g<d.length;g++){var k=d[g];if("string"!==typeof k)return null;k=k.replace(/^"|"$/g,"");k=decodeURIComponent(k).split(",")[0].replace(/^\s+|\s+$/g,"").split(":");if(2===k.length){var q=k[1];switch(k[0]){case "clientRequestGUID":case "g":n.push(q);break;case "btId":case "i":b.push({id:q,duration:-1,ert:-1});break;case "btDuration":case "d":if(0===b.length)return null;k=a.utils.Wb(q);if(!a.utils.Ab(k)||-1>k)return null;b[b.length-1].duration=k;break;case "btERT":case "e":if(0===b.length)return null;
k=a.utils.Wb(q);if(!a.utils.Ab(k)||-1>k)return null;b[b.length-1].ert=k;break;case "serverSnapshotType":case "s":c=q;break;case "hasEntryPointErrors":case "h":e=q}}}return 0===n.length?null:{B:n,btTime:b,serverSnapshotType:c,hasEntryPointErrors:e}};c.nf=e})(a.correlation||(a.correlation={}))}(g||(g={})),function(a){var c=a.conf||(a.conf={});c.ef=3E3;c.$e=a.isDebug;c.ed=1E3;c.Dc=2;c.Cc=5;c.xc=5;c.yc=20;c.Ta=5E3;c.Oc=140;c.Wa=10;c.Mc=30;c.Qc=10;c.Rc=30;c.Nc=30;c.Pc=20;c.Ic=100;c.Va=2048;c.Tc=2048;c.je=
{eumAppKey:"ky",userPageName:"un",clientRequestGUID:"cg",otherClientRequestGUIDs:"og",baseGUID:"bg",parentGUID:"mg",parentPageUrl:"mu",parentPageType:"mt",parentLifecyclePhase:"pp",pageType:"pt",pageUrl:"pu",pageReferrer:"pr",pageTitle:"pl",navOrXhrMetrics:"mn",resourceTimingInfo:"rt",cookieMetrics:"mc",userData:"ud",errors:"er",ajaxError:"ae",btTime:"bt",serverSnapshotType:"ss",hasEntryPointErrors:"se",dataType:"dt",geoCountry:"gc",geoRegion:"gr",geoCity:"gt",localIP:"lp",ip:"ip",BEACONS:"B",ver:"vr",
eom:"em"}}(g||(g={})),function(a){(function(a){var e=function(){function a(){this.Pb=/;jsessionid=[^/?]+/}a.Ne=function(d){for(var a=0,n=0;n<d.length;n++)a=(a<<5)-a+d.charCodeAt(n),a|=0;return a};a.prototype.h=function(d){if(null===d||void 0===d)return null;var a=d.match(this.Pb);if(null!=a){var n=d.indexOf("?");if(0>n||n>a.index)return d.replace(this.Pb,"")}return d};a.prototype.mb=function(d){if(null===d||void 0===d)return null;var a=d.indexOf("?"),n=d.indexOf("#");0>a&&(a=Number.MAX_VALUE);0>n&&
(n=Number.MAX_VALUE);return d.substring(0,Math.min(a,n))};a.prototype.ve=function(d){if(null===d||void 0===d)return null;var f=this.mb(d);return f+"?"+a.Ne(d.substring(f.length))};return a}();a.hf=e;a.e=new e})(a.utils||(a.utils={}))}(g||(g={})),function(a){(function(a){var e=function(){function a(){}a.prototype.ca=function(d,a){if(d)return d.slice(0,a)};return a}();a.nc=e})(a.events||(a.events={}))}(g||(g={})),function(a){(function(a){var e=function(){function a(){}a.ua=function(d){return d.duration?
d.duration:d.responseEnd&&d.startTime?d.responseEnd-d.startTime:-1};return a}();a.ja=e})(a.events||(a.events={}))}(g||(g={})),function(a){(function(a){var e=function(){function b(){}b.prototype.ca=function(d,f){if(d){if(d.length<=f)return d;for(var n=[],b=0;b<d.length;b++)n.push({Ca:d[b],index:b});n.sort(function(d,f){return-(a.ja.ua(d.Ca)-a.ja.ua(f.Ca))});n=n.slice(0,f);n.sort(function(a,d){return a.index-d.index});for(var e=[],b=0;b<n.length;b++)e.push(n[b].Ca);return e}};return b}();a.ab=e})(a.events||
(a.events={}))}(g||(g={})),function(a){(function(a){var e=function(){function b(){}b.prototype.ca=function(d,f){if(d){if(d.length<=f)return d;for(var n=1,b=Math.floor(Number.MAX_VALUE/4),e=d.length;n<b;){for(var g=d.length-1;0<=g;g--)if(a.ja.ua(d[g])<n&&(d.splice(g,1),e--),e<=f)return d;n*=4}return(new a.ab).ca(d,f)}};return b}();a.Yc=e})(a.events||(a.events={}))}(g||(g={})),function(a){(function(c){var e=function(){function d(f,n){this.version=2;this.resourceTimingInfo={};this.yb={};this.zb={};this.Qb=
{};this.Rb={};this.sa={};this.Da=[];this.kd=function(d,f){if(d&&f&&0<f.length){this.Se=d;for(var n=new b,e=new b,c=0;c<f.length;c++){var l=f[c],g=a.utils.parseURI(a.utils.e.h(l.name)),x=l.initiatorType,t=this.sb(g),v=this.Nd(l),r=this.Qd(v,l),s=r?Math.round(r):r;this.Da.push({u:this.Xe(g),i:n.qb(this.zb,x),r:e.qb(this.Rb,t),f:v,o:0===c&&l.isBase?1:s,m:this.Od(v,r,l)})}}};this.sa[d.O]=d.Zc;this.sa[d.L]=d.fc;var e=d.Jd();this.R(e,f);f=this.He(e,f);this.kd(n||a.monitor.perfMonitor.navTiming&&a.monitor.perfMonitor.navTiming.navigationStart,
f)}d.Wd=function(){for(var f=0;f<d.Qa.length;f++)d.n[d.Qa[f]]=d.j.pc;for(f=0;f<d.Oa.length;f++)d.n[d.Oa[f]]=d.j.mc;d.n.js=d.j.$c;d.n.css=d.j.CSS;d.n.svg=d.j.ad;d.n.html=d.j.Pa;d.n.htm=d.j.Pa;f=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.sampler;d.De=f&&"FirstN"==f?new c.nc:f&&"TopN"==f?new c.ab:new c.Yc};d.prototype.wb=function(a,d){a[d]=a[d]?a[d]+1:1};d.prototype.Nd=function(a){return a.fetchStart<=a.domainLookupStart?d.O:d.L};d.prototype.Qd=function(f,n){if(f==d.O||f==
d.L)return n.startTime;a.error("M63",f)};d.prototype.Od=function(f,n,b){function e(a){c.push(0==b[a]?-1:Math.round(b[a]-n))}var c=[];f==d.O?(e("startTime"),e("redirectStart"),e("redirectEnd"),e("fetchStart"),e("domainLookupStart"),e("domainLookupEnd"),e("connectStart"),e("connectEnd"),e("requestStart"),e("responseStart"),e("responseEnd")):f==d.L?(e("startTime"),e("fetchStart"),e("responseEnd")):a.error("M64",f);return c};d.prototype.K=function(a,d){if(3>=d)return"...";a.length>d&&(a=a.substring(0,
d-3)+"...");return a};d.prototype.Ve=function(a,d){if(3>=d)return"...";a.length>d&&(a=a.substring(0,(d-3)/2)+"..."+a.substring(a.length-(d-3)/2,a.length));return a};d.prototype.We=function(d){d.length<=a.conf.Wa||(d=this.K(d,a.conf.Wa-1),d+=":");return d};d.prototype.Ue=function(d,b,e){d=this.We(d);b=this.K(b,a.conf.Mc);e=this.K(e,a.conf.Qc);return 0<e.length?d+"//"+b+":"+e:d+"//"+b};d.prototype.Xe=function(d){function b(){return 0==h.length?e+k+c+g:e+h.join("/")+"/"+k+c+g}var e=this.Ue(d.protocol,
d.hostname,d.port),c=this.K(d.search,a.conf.Rc),g=this.K(d.hash,a.conf.Nc),h=d.pathname.split("/"),k="";0<h.length&&(k=h.pop(),k=this.Ve(k,a.conf.Pc));for(d=b();d.length>a.conf.Oc;){if(0>=h.length)return a.error("M65"),null;h.pop();h.push("...");d=b();h.pop()}return d};d.prototype.sb=function(a){var b;return(a=a.pathname)&&-1!=(b=a.lastIndexOf("."))?d.n[a.substring(b+1,a.length).toLowerCase()]||d.j.Za:d.j.Za};d.prototype.R=function(d,a){d&&this.xb(d);if(a&&0<a.length)for(var b=0;b<a.length;b++)this.xb(a[b])};
d.prototype.xb=function(d){var b=a.utils.parseURI(a.utils.e.h(d.name)),b=this.sb(b);this.wb(this.yb,d.initiatorType);this.wb(this.Qb,b)};d.prototype.He=function(f,b){if(b&&0<b.length){var e=a.conf.userConf&&a.conf.userConf.resTiming&&a.conf.userConf.resTiming.maxNum||a.conf.Ic;f&&e--;b=d.De.ca(b,e);f&&b.unshift(f)}return b};d.prototype.build=function(){return 0==this.Da.length?null:{v:this.version,ic:this.yb,it:this.zb,rc:this.Qb,rt:this.Rb,f:this.sa,t:this.Se,r:this.Da}};d.Jd=function(){var d=a.monitor.perfMonitor.navTiming,
b=null;if(d){var b={},e;for(e in d)d.hasOwnProperty(e)&&(b[e]=d[e]);b.initiatorType="other";b.name=document.URL;b.navigationStart&&!b.startTime&&(b.startTime=b.navigationStart);b.isBase=!0}return b};d.O=1;d.L=2;d.Zc="startTime redirectStart redirectEnd fetchStart dnsLookupStart dnsLookupEnd connectStart connectEnd requestStart responseStart responseEnd".split(" ");d.fc=["startTime","fetchStart","responseEnd"];d.j={pc:"img",$c:"script",CSS:"css",ad:"svg",Pa:"html",mc:"font",Za:"other"};d.Qa="bmp gif jpeg jpg png webp".split(" ");
d.Oa=["ttf","woff","otf","eot"];d.n={};return d}();c.ResourceTimingInfoBuilder=e;var b=function(){function d(){this.oe=1}d.prototype.qb=function(d,a){d[a]||(d[a]=this.oe++);return d[a]};return d}();e.Wd()})(a.events||(a.events={}))}(g||(g={})),function(a){a=a.beacons||(a.beacons={});a.numBeaconsSent=0;a.beaconsSent=[]}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.send=function(d,f){var b=(f?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.corsEndpointPath+"/"+a.conf.appKey+
"/adrum",e;a.utils.va(a.xhrConstructor)&&a.utils.va(a.xhrOpen)?(e=new a.xhrConstructor,a.xhrOpen.call(e,"POST",b)):(e=new XMLHttpRequest,e.open("POST",b));e.setRequestHeader("Content-type","text/plain");var g=a.utils.Yb(d);null!=g&&(e.send(g),a.log("M66"+b+"\n"),a.log("<hr/>"),a.isDebug&&c.beaconsSent.push(d),c.numBeaconsSent+=1)};return b}();c.ec=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){a=a.lc||(a.lc={});a[a.BASE_PAGE=0]="BASE_PAGE";a[a.IFRAME=1]="IFRAME";a[a.XHR=2]="XHR";a[a.VIRTUAL_PAGE=
3]="VIRTUAL_PAGE";a[a.PAGE_ERROR=4]="PAGE_ERROR"}(g||(g={})),function(a){var c=function(){function e(a){this.p=a.p;this.U=a.U}e.prototype.tb=function(){var b=this.Rd();return b&&b.correlation.getPageGUID()||a.correlation.getPageGUID()};e.prototype.Rd=function(){return this.U&&this.U.ADRUM||null};return e}();a.bc=c}(g||(g={})),function(a){a.beacons||(a.beacons={})}(g||(g={})),function(a){(function(a){var e=function(){function a(){this.count=0;this.D={}}a.prototype.F=function(d){if(Object.prototype.hasOwnProperty.call(this.D,
d))return this.D[d];this.D[d]=this.count;this.count++;return this.count-1};a.prototype.pb=function(){var d=[],a;for(a in this.D)Object.prototype.hasOwnProperty.call(this.D,a)&&(d[this.D[a]]=a);return d};return a}();a.Sa=e})(a.utils||(a.utils={}))}(g||(g={})),function(a){(function(a){var e=function(){function a(){}a.Oe=function(a){a=a||"";var f=a.match(/([^:\/?#]+:\/\/)?([^?#]+)?(\?[^#]+)?(#.+)?/);return f&&f[0]==a?(a={},f[1]&&(a.protocol=f[1].substring(0,f[1].length-3)),f[2]&&(a.path=f[2]),f[3]&&
(a.Ob=f[3].substring(1)),f[4]&&(a.anchor=f[4].substring(1)),a):null};a.Bd=function(d,f){var e=a.Oe(d);if(null!=e){var c="";e.protocol&&(c+=f.F(e.protocol),c+="://");if(e.path)for(var g=e.path.split("/"),p=g.length,h=0;h<p;h++){var k=g[h];0<k.length&&(c+=f.F(k));h!=p-1&&(c+="/")}e.Ob&&(c=c+"?"+f.F(e.Ob));e.anchor&&(c+="#",c+=f.F(e.anchor));return c}return""+f.F(d)};a.Ad=function(a,f){return""+f.F(a)};return a}();a.Na=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){(function(c){(function(e){function b(){var b=
null;if("undefined"!==typeof localStorage&&localStorage&&"undefined"!==typeof JSON&&JSON&&"function"===typeof JSON.stringify&&JSON.parse){var e=localStorage[f];if(e)try{b=JSON.parse(e)}catch(c){a.exception(c,"M67"),localStorage.removeItem(f)}else b={clientId:a.utils.generateGUID(),seqId:0},d(b)}else a.log("EXT~: localStorage, JSON or JSON.parse does not exist, cannot get clientInfo");return b}function d(d){"undefined"!==typeof localStorage&&localStorage&&"undefined"!==typeof JSON&&JSON&&"function"===
typeof JSON.stringify&&JSON.stringify?localStorage[f]=JSON.stringify(d):a.log("EXT~: localStorage, JSON or JSON.stringify does not exist, cannot save to localStorage")}var f="ADRUM_CLIENTINFO";e.ob=function(){var f=null,e=b();e&&(e.clientId||(e.clientId=a.utils.generateGUID(),d(e)),f=e.clientId);return f};e.Ld=function(){var a=b(),f=-1;a&&(f=a.pf++,d(a));return f};e.Md=function(){return(new Date).getTime()}})(c.H||(c.H={}))})(a.J||(a.J={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}
b.prototype.za=function(d,f,e){d={ver:a.conf.agentVer,dataType:"R",rootGUID:e.tb(),events:d};a.J.H.ob()&&(d.clientId=a.J.H.ob());f&&(d.geo=f);return b.Ae(d)};b.Ae=function(d){var f=new a.utils.Sa,e=new a.utils.Sa;d=a.utils.Zb(null,d,function(d,g){"string"==typeof g&&g.length>a.conf.Va&&(g=g.substr(0,a.conf.Va));b.fe(d)&&(g=c.Na.Bd(g,f));b.Zd(d)&&(g=c.Na.Ad(g,e));return g});d.guids=e.pb();d.urlParts=f.pb();return d};b.fe=function(a){return"eventUrl"==a||"parentUrl"==a||"pageReferrer"==a||"pageUrl"==
a||"u"==a};b.Zd=function(a){return"eventGUID"==a||"parentGUID"==a||"rootGUID"==a||"clientRequestGUID"==a};return b}();c.dc=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.send=function(a,f){for(var b=0;b<a.length;b++)this.Ie(a[b],f)};b.prototype.Ie=function(d,f){var b=(f?a.conf.beaconUrlHttps:a.conf.beaconUrlHttp)+a.conf.imageEndpointPath,e=new Image;try{e.src=b+d}catch(g){}a.isDebug&&c.beaconsSent.push(d);c.numBeaconsSent+=1};return b}();
c.tc=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){a.events||(a.events={})}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.we=function(d,f){var b=!1;if(null!=d&&a.utils.wa(d)){var e=a.utils.Yb(d);if(null==e||e.length<=f)b=!0}b||(a.log("User event info dropped because they are malformed or too long"),"undefined"!==typeof console&&"undefined"!==typeof console.log&&console.log("User event info dropped because they are malformed or too long"));return b};b.Td=function(d,
f){var e={},c=d&&d.userEventInfo&&d.userEventInfo.PageLoad;return c?(e=a.utils.Bb(c)?c.call(null,e):c,b.we(e,f)?e:{}):{}};return b}();c.cd=e})(a.events||(a.events={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.setPageName=function(a){b.userPageName=a};b.addUserData=function(a,f){b.userData=b.userData||{};b.userData[a]=f};b.prototype.make=function(){var d=this.Pd(),f=this.Kd();a.conf.viz&&(d&&a.utils.ra(document.getElementById(a.conf.viz),d,"navtime"),a.utils.ra(document.getElementById(a.conf.viz),
f,"cookie"));f.PLC=1;d&&(d.PLC=1);0<a.monitor.ErrorMonitor.errorsSent&&(f.EPM=1,d&&(d.EPM=1));f={eventGUID:a.correlation.getPageGUID(),eventUrl:a.utils.e.h(document.URL),eventType:a.utils.compareWindows(top,window)?0:1,cookieMetrics:f};d&&(f.metrics=d);document.referrer&&null!==document.referrer&&0<document.referrer.length&&(f.pageReferrer=a.utils.e.h(document.referrer));document.title&&null!==document.title&&0<document.title.length&&(f.pageTitle=document.title);d=a.correlation.ub();null!==d&&(f.serverMetadata=
d);d=a.monitor.perfMonitor.resTiming?(new c.ResourceTimingInfoBuilder(a.monitor.perfMonitor.resTiming)).build():null;null!==d&&(f.resourceTimingInfo=d);d=c.cd.Td(a.conf.userConf,a.conf.Tc);f.userPageName=b.userPageName||d.userPageName;f.userData=b.userData||d.userData;return f};b.prototype.Pd=function(){if(!a.monitor.perfMonitor.navTiming)return null;var d={};b.rb(a.monitor.perfMonitor.navTiming,d,"NT").add("PLT","navigationStart","loadEventEnd").add("FBT","navigationStart","responseStart").add("SCT",
"navigationStart","requestStart").add("SHT","secureConnectionStart","connectEnd").add("DLT","domainLookupStart","domainLookupEnd").add("TCP","connectStart","connectEnd").add("RAT","requestStart","responseStart").add("FET","responseStart","loadEventEnd").add("DRT","responseStart","domContentLoadedEventStart").add("DDT","responseStart","responseEnd").add("DPT","responseEnd","domContentLoadedEventStart").add("PRT","domContentLoadedEventStart","loadEventEnd").add("DOM","navigationStart","domContentLoadedEventStart");
return d};b.prototype.Kd=function(){var d={};a.commands.marks&&b.rb(a.commands.marks,d,"CK").add("PLT","starttime","onload").add("FBT","starttime","firstbyte").add("FET","firstbyte","onload").add("DRT","firstbyte","onready").add("PRT","onready","onload").add("DOM","starttime","onready");return d};b.jd=function(d,f,b,e,c,g){f=e[f];b=e[b];f&&b?c[d]=b-f:a.log("M68",g,d,f,b)};b.rb=function(a,f,e){var c={add:function(g,p,h){b.jd(g,p,h,a,f,e);return c}};return c};return b}();c.N=e})(a.events||(a.events=
{}))}(g||(g={})),function(a){(function(c){(function(e){function b(f,e){var x,t=e[f],h=typeof t;q.push(f);var m=k[q.join(".")];if(a.utils.Bb(m))x=m(t);else switch(h){case "string":x="number"==typeof m?p(t,d,m):d(t);break;case "number":x=g(t);break;case "object":if(t)if(a.utils.isArray(t))x=c(t,!1,!1);else{x=[];for(var s in t)Object.prototype.hasOwnProperty.call(t,s)&&(h=b(s,t))&&x.push({W:s,v:h});if("navOrXhrMetrics"==f||"cookieMetrics"==f){for(t=0;t<x.length;t++)x[t]=x[t].W+d(":")+x[t].v;x=d("{")+
x.join(d(","))+d("}")}else{for(t=0;t<x.length;t++)s=x[t],h=s.W,a.conf.$e||((m=a.conf.je[s.W])?h=m:a.error("M69",s.W)),x[t]=h+"="+s.v;x=x.join("&")}}else x=null}q.pop();return x}function d(a){return"undefined"===typeof a||null===a||0===a.length?null:encodeURIComponent(a)}function f(a){return encodeURIComponent(encodeURIComponent(a))}function c(a,f,e){void 0===f&&(f=!1);void 0===e&&(e=!0);if(0===a.length)return null;var g=[];if(f)g=a;else for(f=0;f<a.length;f++)g.push(b(f,a));return d("[")+g.join(d(","))+
d(e?">":"]")}function g(a){a=Math.round(a);a<e.Ya&&(a=e.Ya);a>e.Ua&&(a=e.Ua);return d(a)}function m(a,f){if(a>f||0>a)a=e.Uc;return d(a)}function p(d,f,b,e){void 0===e&&(e=!0);if("undefined"===typeof d||null===d||0===d.length)return null;var c=3<=b?"...":"";a.assert(b>=c.length);for(var g=!1,n=null;;){try{n=f(d);if(null===n)return null;if(n.length<=b)break}catch(k){}var l;g?l=d.length-1:(g=!0,l=b-=c.length);var h=e?0:Math.max(d.length-l,0);d=d.substr(h,l)}g&&(n=e?n+c:c+n);return n}function h(d,f,b){if(0==
b)return e.ha;if(f<d)return 0;f=e.ha+(f-d)/b;a.assert(f>=e.ha);a.log("M70",d,f);return f}e.Uc=-1;e.ia=180;e.Kc=50;e.Lc=50;e.Fc=40;e.ha=50;e.uc=50;e.Xa=128;e.Ac=30;e.Bc=30;e.zc=30;e.Gc=8;e.Ya=-99999;e.Ua=999999;e.vc=2E3;e.Jc=2;e.wc=99999999;var k={".pageUrl":e.ia,".parentPageUrl":e.ia,".pageReferrer":e.ia,".pageTitle":e.Kc,".userPageName":e.Lc,".geoCountry":e.Ac,".geoRegion":e.Bc,".geoCity":e.zc,".localIP":e.Gc,".otherClientRequestGUIDs":function(a){a=a||[];var d=a.slice(0,e.Jc);return c(d,!1,d.length<
a.length)},".btTime":function(d){d=d||[];for(var f=d.slice(0,a.conf.xc),b=[],k=0;k<f.length;k++){var h=f[k];b.push(c([m(Number(h[0]),e.wc),g(h[1]),g(h[2])],!0,!1))}return c(b,!0,f.length<d.length)},".ajaxError":function(a){return c([f(a[0]),p(a[1],f,e.uc)],!0,!1)},".userData":function(a){a=a||[];for(var d=!1,b=0,g=[],k=0;k<a.length;k++){var l=a[k];g[k]=c([f(l[0]),f(l[1])],!0,!1);b+=g[k].length;if(b>e.Xa){d=!0;break}}for(;;){a=c(g,!0,d);if(null===a||a.length<=e.Xa)return a;g.pop();d=!0}}},q=[];e.zd=
function(d,k){void 0===k&&(k=!0);q=[];var m=[];d.errors&&(m=d.errors,d.errors=null);var t=b("",{"":d});if(m&&0<m.length){for(var v=h(k?870:354,e.vc-t.length,m.length),r=[],s=0;s<m.length;s++){var w=m[s],y=a.utils.e.mb(a.utils.e.h(w[0]));r.push(c([p(y,f,e.Fc,!1),g(w[1]),p(w[2],f,v)],!0,!1))}m=c(r,!0,!1);t+="&errors="+m}return t};e.lf=b;e.qf=d;e.element=f;e.jf=c;e.kf=g;e.mf=m;e.truncate=p;e.of=h})(c.Ra||(c.Ra={}))})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}
b.prototype.za=function(d,f,e){for(var g=[],m=[],p=null,h=[],k=0;k<d.length;k++){var q=d[k];if(4===q.eventType){var u=q;m.push([q.eventUrl,u.line,u.message])}else{if(0===q.eventType||1===q.eventType)p=q;h.push(q)}}d=h;if(0<m.length)for(p&&(p.errors=m.splice(0,a.conf.Dc));0<m.length;)q=m.splice(0,a.conf.Cc),p=b.ze.make(),p.errors=q,p.isErrorEvent=!0,p.cookieMetrics=null,p.metrics=null,p.resourceTimingInfo=null,d.push(p);for(m=0;m<d.length;m++)q=d[m],a.log("M71"),q.resourceTimingInfo=null,b.Gd(q,f,
e),p=b.transform(q),g.push(c.Ra.zd(p,q.isErrorEvent));return g};b.Gd=function(d,f,b){d.ver=this.qc;d.rootGUID=b.tb();d.geo=f;d.dataType="R";d.eom=1;d.eumAppKey=a.conf.appKey;d.PLC=1};b.transform=function(a){var f={};b.ac("",{"":a},f);return f};b.ac=function(d,f,e){f=f[d];var c=b.Fb[d];if("metrics"===d||"cookieMetrics"===d)e[c]=f;else if("btTime"===d&&a.utils.isArray(f)&&0<f.length){d=[];for(var g=0;g<f.length;g++)d.push([f[g].id,f[g].duration,f[g].ert]);e[c]=d}else if("userData"===d&&a.utils.wa(f))e[c]=
a.utils.ke(f);else if(a.utils.wa(f))for(g in f)Object.prototype.hasOwnProperty.call(f,g)&&b.ac(g,f,e);else b.Fb[d]&&("eventType"===d&&2<f&&(f=a.utils.compareWindows(top,window)?0:1),e[c]=f)};b.ze=new a.events.N;b.qc=3;b.Fb={eumAppKey:"eumAppKey",userPageName:"userPageName",rootGUID:"baseGUID",parentGUID:"parentGUID",parentUrl:"parentPageUrl",parentType:"parentPageType",parentLifecyclePhase:"parentLifecyclePhase",eventType:"pageType",eventUrl:"pageUrl",pageReferrer:"pageReferrer",pageTitle:"pageTitle",
metrics:"navOrXhrMetrics",xhrMetrics:"navOrXhrMetrics",resourceTimingInfo:"resourceTimingInfo",cookieMetrics:"cookieMetrics",userData:"userData",errors:"errors",ajaxError:"ajaxError",dataType:"dataType",country:"geoCountry",region:"geoRegion",city:"geoCity",localIP:"localIP",ver:"ver",eom:"eom",eventGUID:"clientRequestGUID",otherClientRequestGUIDs:"otherClientRequestGUIDs",btTime:"btTime",serverSnapshotType:"serverSnapshotType",hasEntryPointErrors:"hasEntryPointErrors"};return b}();c.sc=e})(a.beacons||
(a.beacons={}))}(g||(g={})),function(a){(function(a){var e=function(){function a(){}a.prototype.send=function(){};return a}();a.kc=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){(function(a){var e=function(){function a(){}a.prototype.za=function(){return null};return a}();a.jc=e})(a.beacons||(a.beacons={}))}(g||(g={})),function(a){var c=function(){function e(){}e.gb=function(b,d){if(!b)return null;var f=b.ADRUM.lifecycle;if(!f||!f.getPhaseCallbackTime)return null;var e=d.getPhaseCallbackTime("AT_ONLOAD"),
f=f.getPhaseCallbackTime("AT_ONLOAD"),c=null==f;return null==e?(a.error("M72"),null):a.lifecycle.getPhaseID(c||e<=f?"AFTER_FIRST_BYTE":"AFTER_ONLOAD")};return e}();a.Wc=c;a.cPLPI=c.gb}(g||(g={})),function(a){(function(c){var e=function(){function b(a){this.ready=!1;this.geoResolverUrl=a}b.prototype.init=function(d){this.channel=d;if(this.geoResolverUrl){a.geo={failed:!1,result:null};a.utils.loadScriptAsync(this.geoResolverUrl+"/resolve.js");var f=this;a.utils.Ye(b.ld,function(){return f.isReady()},
function(){f.onReady()},function(){f.ye()})}else this.ready=!0,d.onResolverReady()};b.prototype.isReady=function(){this.ready||(this.ready=a.geo&&(a.geo.failed||null!==a.geo.result))||a.log("M73");return this.ready};b.prototype.onReady=function(){a.geo.failed?a.log("M74"):(a.assert("object"===typeof a.geo.result),a.log("M75",a.geo.result));a.geo&&a.geo.result&&this.channel.Ke(a.geo.result);this.channel.onResolverReady()};b.prototype.ye=function(){a.log("M76");this.ready=!0;this.channel.onResolverReady()};
b.ld=function(a){return 10<a?-1:[1,50,100,500][a-1]||1E3};return b}();c.oc=e})(a.channel||(a.channel={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){this.ready=!1;this.channel=null}b.prototype.init=function(d){this.channel=d;b.g=b.nb();this.ready=!b.g.p;var f=this;if(b.g.p)a.log("M77"),b.g.p.ADRUM.command("listenForOkToSendChildFrameBeacons",function(){a.log("M78");f.ready=!0;f.onReady()});else f.onReady()};b.prototype.isReady=function(){this.isReady||a.log("M79");return this.ready};
b.prototype.onReady=function(){this.channel.Je(b.g);this.channel.onResolverReady()};b.nb=function(){if(!b.g){for(var d=b.Id(),f=[],e=0;e<d.length;e++)try{d[e].ADRUM&&f.push(d[e])}catch(c){}b.g=new a.bc({p:0<f.length?f[0]:null,U:0<f.length?f[f.length-1]:null})}return b.g};b.Id=function(){for(var d=[],f=window;!a.utils.compareWindows(f,top);)f=f.parent,d.push(f);return d};b.g=null;return b}();c.Ma=e})(a.channel||(a.channel={}))}(g||(g={})),function(a){a.G=null;a.addResolver=null;(function(c){function e(a){return a&&
a.document.URL&&0==a.document.URL.indexOf("https:")}var b=function(){function d(d,b,e){this.events=[];this.S=NaN;this.s=[];this.ta=!1;this.bufferMode=a.conf.userConf&&a.conf.userConf.channel&&"undefined"!==typeof a.conf.userConf.channel.bufferMode?a.conf.userConf.channel.bufferMode:!0;this.da=-1;this.Te=d;this.md=b;this.s.push(new c.oc(e));this.s.push(new c.Ma)}d.create=function(){var f,b;f=c.Ma.nb();b=e(window)||e(f.p);f="undefined"!==typeof JSON&&!(!JSON||!JSON.stringify);b=-1<navigator.userAgent.toLowerCase().indexOf("firefox")&&
b;window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest&&f&&!b&&"true"!==a.conf.sendImageBeacon&&!0!==window["adrum-send-image-beacon"]?(f=new a.beacons.ec,b=new a.beacons.dc):a.conf.userConf&&a.conf.userConf.beacon&&a.conf.userConf.beacon.neverSendImageBeacon?(f=new a.beacons.kc,b=new a.beacons.jc):(f=new a.beacons.tc,b=new a.beacons.sc);f=new d(f,b,a.conf.geoResolverUrl);f.init();return f};d.prototype.init=function(){for(var a=0;a<this.s.length;a++)this.s[a].init(this)};d.prototype.G=function(f){f.sequenceId=
a.J.H.Ld();f.timestamp=a.J.H.Md();this.events.push(f);1==this.events.length&&(this.S=a.utils.now());d.$d(f)&&(this.ta=!0);this.Ia()};d.prototype.be=function(a){return 0===a.eventType||1===a.eventType};d.prototype.nd=function(){for(var d=0;d<this.events.length;d++){var b=this.events[d];if(this.be(b)){var e=this.g.p;null!==e&&(b.parentLifecyclePhase=a.Wc.gb(e,a.lifecycle),b.parentGUID=e.ADRUM.correlation.getPageGUID(),b.parentUrl=a.utils.e.h(e.document.URL),b.parentType=a.utils.compareWindows(top,e)?
0:1)}}};d.prototype.sendBeacon=function(){if(0==this.events.length)a.log("M80");else{this.nd();var d=this.af(this.events,this.g),b=this.md.za(this.events,this.Hd,this.g);this.Te.send(b,d);this.events=[];this.S=Number.POSITIVE_INFINITY}};d.prototype.onResolverReady=function(){this.Ia()};d.prototype.Ke=function(a){this.Hd=a};d.prototype.Je=function(a){this.g=a};d.prototype.addResolver=function(a){a.init(this);this.s.push(a)};d.prototype.Ce=function(){for(var a=0;a<this.s.length;a++)if(!this.s[a].isReady())return!1;
return!0};d.prototype.Eb=function(){return this.S+a.conf.Ta>a.utils.now()};d.prototype.de=function(){return this.events.length<a.conf.yc};d.prototype.af=function(a,d){for(var b=!1,c=0;c<a.length;c++){var g=a[c];if(g.eventUrl&&0==g.eventUrl.indexOf("https:")){b=!0;break}}return b||e(d.p)};d.prototype.Ia=function(){if(this.Ce())if(this.cf()){if(this.Eb()&&0<this.events.length&&0>this.da){var d=this;this.da=setTimeout(function(){d.Ia()},a.conf.Ta+this.S-a.utils.now())}}else clearTimeout(this.da),this.da=
-1,this.ta=!1,this.sendBeacon()};d.$d=function(a){return 0===a.eventType||1===a.eventType||3===a.eventType};d.prototype.cf=function(){return this.bufferMode&&!this.ta&&this.de()&&this.Eb()};return d}();c.Channel=b;(function(){var d=b.create();a.G=function(a){d.G(a)};a.report=a.G;a.addResolver=function(a){d.addResolver(a)};a.addResolver=a.addResolver})()})(a.channel||(a.channel={}))}(g||(g={})),function(a){var c=function(){function e(){}e.Nb=function(){return window.attachEvent?window.addEventListener?
this.Ja:this.Xb:this.$b};e.Mb=function(b){var d=null;switch(e.Nb()){case e.$b:d=b.parentPhase;break;case e.Ja:d=a.lifecycle.findPhaseAtNominalTime(b.sendTime);break;case e.Xb:d=null}return a.lifecycle.getPhaseID(d)};e.$b="uCT";e.Ja="uNET";e.Xb="tIA";return e}();a.P=c}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.make=function(d,f){var e=d.getAllResponseHeaders(),c=d.status,g=400<=c?d.responseText:null;a.assert(null!==f.url&&null!==f.sendTime&&null!==f.firstByteTime&&
null!==f.respAvailTime&&null!==f.respProcTime,"missing some pieces of XHR data: url="+f.url+", send="+f.sendTime+", fbt="+f.firstByteTime+", rat="+f.respAvailTime+", eut="+f.respProcTime+", parentPhase="+f.parentPhase);if(null===f.url||null===f.sendTime||null===f.firstByteTime||null===f.respAvailTime||null===f.respProcTime)return null;var p=null;400<=c&&(p=[c,g||""]);c={PLC:1,FBT:f.firstByteTime-f.sendTime,DDT:f.respAvailTime-f.firstByteTime,DPT:f.respProcTime-f.respAvailTime,PLT:f.respProcTime-f.sendTime,
ARE:p?1:0};g=a.utils.getFullyQualifiedUrl(f.url);if(!b.ge(c,g))return null;a.conf.viz&&a.utils.ra(document.getElementById(a.conf.viz),c,"xhr");var e=a.correlation.Sd(e),h=null,h=e&&null!==e&&null!==e.clientRequestGUID?e.clientRequestGUID:a.utils.generateGUID(),c={eventType:2,eventGUID:h,eventUrl:a.utils.e.h(g),parentGUID:f.parentGUID?f.parentGUID:a.correlation.getPageGUID(),parentUrl:a.utils.e.h(f.parentUrl?f.parentUrl:document.URL),parentType:f.parentType?f.parentType:0,parentLifecyclePhase:f.Lb,
metrics:c,method:f.method};null!==e&&(c.serverMetadata=e);null!==p&&(c.ajaxError=p);return c};b.ge=function(d,f){for(var b in d)if(d.hasOwnProperty(b)){var e=d[b];if(0>e)return a.error("XHR "+b+" ["+e+"] "+f),!1}return!0};return b}();c.gd=e})(a.events||(a.events={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.make=function(d,f,b,e){d={eventGUID:a.utils.generateGUID(),eventUrl:a.utils.e.h(f),eventType:4,parentGUID:a.correlation.getPageGUID(),parentUrl:a.utils.e.h(document.URL),
parentType:a.utils.compareWindows(top,window)?0:1,message:d,line:b};null!==e&&(d.stack=e);a.G(d)};return b}();c.Vc=e})(a.events||(a.events={}))}(g||(g={})),function(a){a.events||(a.events={})}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.make=function(d){var f={eventGUID:d.getGUID(),parentGUID:a.correlation.getPageGUID(),eventUrl:a.utils.e.h(d.getLocationUrl()),eventType:3,pageUrl:a.utils.e.h(d.getRouteUrl()),pageName:d.getName(),metrics:d.buildMetrics()};d=(new c.ResourceTimingInfoBuilder(d.buildResourceTimingInfo())).build();
null!==d&&(f.resourceTimingInfo=d);return f};return b}();c.dd=e})(a.events||(a.events={}))}(g||(g={})),function(a){a=a.events||(a.events={});var c=a.Z||(a.Z={});c.PageLoad={maker:new a.N};c.XHR={maker:new a.gd};c.VPLoad={maker:new a.dd};c.PageError={maker:new a.Vc}}(g||(g={})),function(a){(function(c){function e(b){for(var d=[],f=1;f<arguments.length;f++)d[f-1]=arguments[f];f=a.events.Z[b].maker;return f.make.apply(f,d)}c.reportEvent=function(b){for(var d=1;d<arguments.length;d++);d=a.events.Z[b];
(d=!(!d||!d.maker))||a.log("M82"+b);d&&(d=e.apply(null,arguments),!a.utils.va(d)||a.conf.userConf&&a.conf.userConf.reporter&&a.conf.userConf.reporter.filter&&!a.conf.userConf.reporter.filter(d)||(a.log("M81"+b+" event"),a.G(d)))}})(a.reporter||(a.reporter={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){this.ready=!1}b.prototype.onReady=function(a){this.ready=a;this.channel.onResolverReady()};b.prototype.isReady=function(){this.ready||a.log("M83");return this.ready};b.prototype.init=
function(a){this.channel=a};return b}();c.fd=e})(a.commands||(a.commands={}))}(g||(g={})),function(a){(function(c){var e=new c.fd;a.addResolver(e);c.marks={};c.mark=function(b,d){a.log("M84",b,d);c.marks[b]=d};c.reportOnload=function(){setTimeout(function(){a.log("M85");e.onReady(!0);a.reporter.reportEvent("PageLoad")},a.conf.ed)};c.reportEvent=function(){a.reporter.reportEvent.apply(a.reporter,arguments)};c.addResolver=function(b){a.addResolver(b)};c.reportXhr=function(b,d){a.log("M86");a.P.Nb()==
a.P.Ja?(a.log("M87"),setTimeout(function(){d.Lb=a.P.Mb(d);a.reporter.reportEvent("XHR",b,d)},0)):(d.Lb=a.P.Mb(d),a.reporter.reportEvent("XHR",b,d))};c.listenForOkToSendChildFrameBeacons=function(b){a.log("M88");try{b()}catch(d){a.exception(d,"M89")}};c.reportPageError=function(b,d,f,e){a.log("M90",b,d,f,e);d&&0!==d.length||(d="CROSSORIGIN");a.reporter.reportEvent("PageError",b,d,f,e)};c.setPageName=function(b){a.events.N.setPageName(b)};c.addUserData=function(b,d){a.events.N.addUserData(b,d)};c.call=
function(a){a()};c.registerEvent=function(b,d){a.events.Z[b]=d}})(a.commands||(a.commands={}))}(g||(g={})),function(a){(function(a){a.lb=function(e){return encodeURIComponent(a.e.ve(e))}})(a.utils||(a.utils={}))}(g||(g={})),function(a){(function(c){var e=function(){function b(){}b.prototype.w=function(){this.le();a.utils.addEventListener(window,"pagehide",b.La);a.utils.addEventListener(window,"beforeunload",b.La);a.utils.addEventListener(window,"unload",b.La)};b.prototype.le=function(){(this.startTime=
b.Fd()||b.Ed())&&a.commands.mark("starttime",this.startTime)};b.Fd=function(){var d;if(window.external&&"undefined"!=typeof window.external&&window.external.pageT&&"undefined"!=typeof window.external.pageT)d=(new Date).getTime()-window.external.pageT;else if(window.T&&"undefined"!=typeof window.T&&window.T.pageT&&"function"===typeof window.T.pageT){var f=window.T.pageT();"number"===typeof f&&(d=(new Date).getTime()-f)}else window.chrome&&"undefined"!=typeof window.chrome&&window.chrome.csi&&"function"===
typeof window.chrome.csi&&(f=window.chrome.csi(),f.pageT&&"number"===typeof f.pageT&&(d=(new Date).getTime()-f.pageT));d&&(d=Math.round(d),a.log("M91",d));return d};b.Ed=function(){var d=a.correlation.startTimeCookie;if(d){a.log("M92",d.startTime,d.startPage);var f=a.utils.lb(document.referrer);if(f===d.startPage)if(isNaN(d.startTime))a.log("M93",d.startTime);else return d.startTime;else a.log("M94",f,d.startPage)}else a.log("M95")};b.vd=function(d,f){var b=document.domain,e="https:"===document.location.protocol,
c="ADRUM=s="+Number(new Date)+"&r="+a.utils.lb(document.location.href),g=c+";path=/";e&&(g+=";secure");a.log("M96",c);if(!a.conf.useStrictDomainCookies){for(var e=d(),b=b.split("."),h="",k=b.length-1;0<=k;k--){h="."+b[k]+h;a.log("M97",h);f(g+";domain="+h);var q=d();if(q!=e&&0<=q.indexOf(c)){a.log("M98");a.log("M99");return}}a.log("M100")}a.log("M101");f(g);a.log("M102")};b.La=function(){var a=!1;return function(){a||(a=!0,b.vd(function(){return document.cookie},function(a){document.cookie=a}))}}();
return b}();c.gf=e;c.Pe=new e})(a.monitor||(a.monitor={}))}(g||(g={})),function(a){a.log("M103");a.monitor.Pe.w();a.q.processQ();a.initEXTDone=!0;a.log("M104")}(g||(g={})))})();})();
